name: bolao_do_frango_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.4.7
  cupertino_icons: ^1.0.5
  dots_indicator: ^2.1.0
  dio: ^4.0.6
  dartz: ^0.10.1
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.2
  flutter_native_splash: ^2.2.9
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  json_annotation: ^4.5.0
  mask_text_input_formatter: ^2.4.0
  mobx: ^2.0.7+2
  sizer: ^2.0.15
  validatorless: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  faker_dart: ^0.1.4
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  mobx_codegen: ^2.0.7

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/images/launcher_icons/launcher_icon_android.png"
  image_path_ios: "assets/images/launcher_icons/launcher_icon_ios.png"
  remove_alpha_ios: true

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/flags/
    - assets/images/launcher_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
